# Generated by Django 4.0.4 on 2022-07-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('questiontype', models.CharField(max_length=100)),
                ('choice1', models.CharField(max_length=5000)),
                ('choice2', models.CharField(max_length=5000)),
                ('choice3', models.CharField(max_length=5000)),
                ('choice4', models.CharField(max_length=5000)),
            ],
        ),
    ]
