# Generated by Django 4.0.4 on 2022-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question2',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
