# Generated by Django 4.0.4 on 2022-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_question2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='choice4a',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question2',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
