# Generated by Django 4.0.4 on 2022-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_survey_choice4a_alter_survey_question2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice1a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice2a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice3a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice4a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question1',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questiontype1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
