# Generated by Django 4.0.4 on 2022-07-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_survey_category_alter_survey_choice1a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
