# Generated by Django 4.0.4 on 2022-07-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_survey_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=10000, null=True)),
                ('choice1a', models.CharField(max_length=5000, null=True)),
                ('choice2a', models.CharField(max_length=5000, null=True)),
                ('choice3a', models.CharField(max_length=5000, null=True)),
                ('choice4a', models.CharField(max_length=5000, null=True)),
                ('question2', models.CharField(max_length=10000, null=True)),
                ('choice1b', models.CharField(max_length=5000, null=True)),
                ('choice2b', models.CharField(max_length=5000, null=True)),
                ('choice3b', models.CharField(max_length=5000, null=True)),
                ('choice4b', models.CharField(max_length=5000, null=True)),
                ('question3', models.CharField(max_length=10000, null=True)),
                ('choice1c', models.CharField(max_length=5000, null=True)),
                ('choice2c', models.CharField(max_length=5000, null=True)),
                ('choice3c', models.CharField(max_length=5000, null=True)),
                ('choice4c', models.CharField(max_length=5000, null=True)),
                ('question4', models.CharField(max_length=10000, null=True)),
                ('choice1d', models.CharField(max_length=5000, null=True)),
                ('choice2d', models.CharField(max_length=5000, null=True)),
                ('choice3d', models.CharField(max_length=5000, null=True)),
                ('choice4d', models.CharField(max_length=5000, null=True)),
                ('question5', models.CharField(max_length=10000, null=True)),
                ('choice1e', models.CharField(max_length=5000, null=True)),
                ('choice2e', models.CharField(max_length=5000, null=True)),
                ('choice3e', models.CharField(max_length=5000, null=True)),
                ('choice4e', models.CharField(max_length=5000, null=True)),
                ('question6', models.CharField(max_length=10000, null=True)),
                ('choice1f', models.CharField(max_length=5000, null=True)),
                ('choice2f', models.CharField(max_length=5000, null=True)),
                ('choice3f', models.CharField(max_length=5000, null=True)),
                ('choice4f', models.CharField(max_length=5000, null=True)),
                ('question7', models.CharField(max_length=10000, null=True)),
                ('choice1g', models.CharField(max_length=5000, null=True)),
                ('choice2g', models.CharField(max_length=5000, null=True)),
                ('choice3g', models.CharField(max_length=5000, null=True)),
                ('choice4g', models.CharField(max_length=5000, null=True)),
                ('question8', models.CharField(max_length=10000, null=True)),
                ('choice2h', models.CharField(max_length=5000, null=True)),
                ('choice1h', models.CharField(max_length=5000, null=True)),
                ('choice3h', models.CharField(max_length=5000, null=True)),
                ('choice4h', models.CharField(max_length=5000, null=True)),
                ('question9', models.CharField(max_length=10000, null=True)),
                ('choice1i', models.CharField(max_length=5000, null=True)),
                ('choice2i', models.CharField(max_length=5000, null=True)),
                ('choice3i', models.CharField(max_length=5000, null=True)),
                ('choice4i', models.CharField(max_length=5000, null=True)),
                ('question10', models.CharField(max_length=10000, null=True)),
                ('choice1j', models.CharField(max_length=5000, null=True)),
                ('choice2j', models.CharField(max_length=5000, null=True)),
                ('choice3j', models.CharField(max_length=5000, null=True)),
                ('choice4j', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
