# Generated by Django 4.0.4 on 2022-07-17 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_remove_survey_questiontype3_survey_bol1_survey_bol10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='bol1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bol9',
        ),
        migrations.AddField(
            model_name='survey',
            name='questiontype3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question1',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question2',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question3',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question4',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question5',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questiontype1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questiontype2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questiontype4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questiontype5',
            field=models.CharField(max_length=100),
        ),
    ]
