# Generated by Django 4.0.4 on 2022-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_survey_bol1_remove_survey_bol10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='choice1j',
            new_name='bol1a',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='choice2j',
            new_name='bol1b',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='choice3j',
            new_name='bol1c',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='choice4j',
            new_name='bol1d',
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1e',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1f',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1g',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1h',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1i',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol1j',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2b',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2c',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2d',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2e',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2f',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2g',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2h',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2i',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol2j',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3b',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3c',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3d',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3e',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3f',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3g',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3h',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3i',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol3j',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4a',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4b',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4c',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4d',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4e',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4f',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4g',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4h',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4i',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='bol4j',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
